site_name: Adam Callison
site_url: https://www.adamcallison.com

nav:
    - Home: index.md
    - Blog: blogs.md
    - Publications: publications.md
    - CV: cv.md
    
theme:
    name: material
    favicon: images/favicon.ico
    logo: images/favicon.ico
    palette:
        primary: red
    features:
        - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - blogging:
      dirs: # The directories to be included
        - blog

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js